  workflow:
    rules:
# Если целевая ветка tis5000 или tis5001
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_PIPELINE_SOURCE == "merge_request_event"
# Если результатом стало объединение
#      - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
# Если открыт Merge Request
#      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
# Если необходима возможность запуска по тригеру
      - if: $CI_PIPELINE_SOURCE == "trigger"
# Если необходима возможность запуска по нажатию кнопки Run pipeline в проекте CI/CD > Pipelines section
      - if: $CI_PIPELINE_SOURCE == "web"
# Если Merge Request был принят "Approve" c 14.1
#      - if: CI_MERGE_REQUEST_APPROVED == "true"
# Если был коммит в ветку dev происходит запуск Pipeline
#      - if: '$CI_COMMIT_BRANCH' == "dev"'
# Если главная ветка проекта будет dev
#      - if: '$CI_DEFAULT_BRANCH == "dev"'

  include:
    # Информирование о статусе pipeline в Telegram
    - project: 'ci_cd/shared/telegram_informer'
      ref: 'master'
      file: 'telegram_informer.yml'

  variables:
    RUN_DIR: "/opt/services/api_video_upload"
    FF_USE_FASTZIP: "true" 
    ARTIFACT_COMPRESSION_LEVEL: "fast" 
    CACHE_COMPRESSION_LEVEL: "fast" 
  
  stages:
    - run
    - clean
    - notify
      
  run_app_dev:
    stage: run
    rules:
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "trigger"
      - if: $CI_PIPELINE_SOURCE == "web"
    script:
      - 'rsync -avO --no-perms --no-owner --no-group --exclude ".git/" $CI_PROJECT_DIR/ $RUN_DIR/'
      - cd $RUN_DIR
      - docker-compose down --rmi all
      - docker-compose up -d
    allow_failure: false
    tags:
      - tis5000

  clean: 
    stage: clean
    script:
      - docker image prune --filter="dangling=true" -f
    allow_failure: true
    
### Информер
  notify-sucess:
    stage: notify
    when: on_success
    extends: .notify-sucess

  notify-failure:
    stage: notify
    when: on_failure
    extends: .notify-failure
