FROM python:3.10.15-slim-bookworm as builder

# install system dependencies
RUN apt-get update

# set Work Directory
WORKDIR /usr/src/app

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

FROM python:3.10.15-slim-bookworm

#Set environment variable
ARG DEBIAN_FRONTEND=noninteractive
#Prevents Python from writing pyc files to disc (equivalent python -B)
ENV PYTHONDONTWRITEBYTECODE 1
#Prevents Python from buffering stdout and stderr (equivalent python -u)
ENV PYTHONUNBUFFERED 1
ENV PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/app/.local/bin

RUN mkdir -p /opt/uploads
WORKDIR /opt/

# add app
COPY api.sh /opt/

# install system dependencies and set Moscow time
RUN apt-get update && \
    apt-get -y install apt-utils tzdata locales nano curl telnet ffmpeg && \
    apt-get clean && apt-get autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/* && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

#Set locale & timezone environment variable
ENV TZ=Europe/Moscow
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# install python dependencies
COPY --from=builder /usr/src/app/wheels /wheels
RUN pip install --upgrade --no-cache setuptools pip && \
    pip install --no-cache /wheels/* && \
	rm -rf /wheels/*
